export const LOGGING_IN = "LOGGING_IN"
export const LOGIN_APP = "LOGIN_APP"
export const GET_ROOM_INFO = 'GET_IMAGE_DATA'
export const REMEMBER_ME = "REMEMBER_ME"
export const REMEMBER_ME_CLEAR = "REMEMBER_ME_CLEAR"

export const SELECT_COMPANY = "SELECT_COMPANY"
export const SELECT_SUBCOMPANY = "SELECT_SUBCOMPANY"
export const RESET_COMPANY = 'RESET_COMPANY';
export const RESET_SELECT_COMPANY = 'RESET_SELECT_COMPANY';
export const RESET_SELECT_SUBCOMPANY = 'RESET_SELECT_SUBCOMPANY';

export const ADD_SUBCOMPANY = 'ADD_SUBCOMPANY';
export const RESET_SUBCOMPANY = 'RESET_SUBCOMPANY';

export const ADD_COMPANY = 'ADD_COMPANY';

export const ROOMTYPE = 'ROOMTYPE';
export const ADD_FETCHED_DATA = 'ADD_FETCHED_DATA';

export const LOGOUT = "LOGOUT"
export const DEVICE_IN = "DEVICE_IN"
export const DEVICE_TYPE = "DEVICE_TYPE"
export const COMPANY_ID = "COMPANY_ID"
export const PARENT_COMPANY_ID = "PARENT_COMPANY_ID"
export const SAVEROOM_ID = "SAVEROOM_ID"

export const RESET_CONTACTS = "RESET_CONTACTS"
export const ADD_CONTACTS = "ADD_CONTACTS"

export const ADD_SELECT_RESIDENT = "ADD_SELECT_RESIDENT"

export const ADD_SELECT = "ADD_SELECT"
export const RESET_SELECT = "RESET_SELECT"

export const ACCOUNT_INFO = "ACCOUNT_INFO"
export const RESIDENT_INFO = "RESIDENT_INFO"
export const RESIDENT_ID = "RESIDENT_ID"
export const CLEAR_RESIDENT = "CLEAR_RESIDENT"

export const RESET_RESIDENTS = "RESET_RESIDENTS"
export const ADD_RESIDENTS_LIST = "ADD_RESIDENTS_LIST"
export const ADD_RESIDENTS = "ADD_RESIDENTS"

export const WIFI_INFO = "WIFI_INFO"

export const ADD_ROOM = "ADD_ROOM"
export const ROOM_ID = "ROOM_ID"

export const CLEAR_OTHER_RESIDENT = "CLEAR_OTHER_RESIDENT"




